"use client";

import * as React from "react";
import { cn } from "@/lib/utils";

interface SmartImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  /** Preferred local /public path (the "large", <=1200px, variant). */
  local: string;
  /** Remote CDN fallback used if the local file is missing. */
  fallback?: string;
  /** Responsive `sizes` hint so the browser picks card vs large from srcset. */
  sizes?: string;
  /** Above-the-fold / LCP image: load eagerly with high fetch priority. */
  priority?: boolean;
}

/** Derive the pre-generated 640px card variant path from a large image path. */
function cardVariant(local: string): string | null {
  if (!/\.jpe?g$/i.test(local)) return null;
  if (/__card\.jpe?g$/i.test(local)) return local;
  return local.replace(/\.jpe?g$/i, "__card.jpg");
}

/** Same path, different codec — generated by scripts/build-image-formats.mjs. */
const asFormat = (jpg: string, ext: "webp" | "avif") =>
  jpg.replace(/\.jpe?g$/i, `.${ext}`);

/**
 * Serve product photography from Shopify's CDN instead of our own /public.
 *
 * Set NEXT_PUBLIC_IMG_CDN=1 (we set it on Vercel). Three reasons this wins in
 * production: the CDN holds the ORIGINALS at 1550x2325 where our local copies
 * are downscaled to 1200x1800, it's geo-distributed, and it keeps ~1.8 GB /
 * 15,912 image files out of the deployment entirely. Locally the flag is off,
 * so `next dev` keeps using the local files (and works offline).
 */
/**
 * Defaults to ON. `public/bertolucci_images` (1.8 GB / 15,912 files) is NOT in
 * the git repo and NOT in the deployment, so a fresh clone on any machine has
 * no local photography — defaulting to the CDN means the site simply works
 * after `git clone && npm install`, with no extra setup.
 *
 * Set NEXT_PUBLIC_IMG_CDN=0 on a machine that DOES have the local library to
 * use it instead (offline dev, or to exercise the local AVIF/WebP ladder).
 */
const USE_CDN = process.env.NEXT_PUBLIC_IMG_CDN !== "0";

/**
 * Rungs offered to the browser in CDN mode.
 *
 * The old ladder started at 640w, which was the smallest thing on offer for a
 * PDP thumbnail that needs ~193 device px and for a mobile product card that
 * needs ~430 — so the browser correctly picked 640w and we shipped four to
 * eleven times the pixels actually painted. The measured needs across the site
 * cluster at roughly 190 / 390-480 / 580 / 765 / 940-1110, which is what these
 * rungs bracket. Only 240, 480 and 900 are new; 640/1200/1550 are unchanged.
 *
 * DEPLOY NOTE: Shopify generates a resized variant lazily. The FIRST request for
 * a width that has never been asked for takes ~479 ms while the CDN renders it,
 * then it is edge-cached like any other asset. Three new widths across the
 * catalogue therefore means a one-off warm-up cost on the first visitor to hit
 * each image at each new width, not a recurring one. Plan for it (a crawl of
 * /shop + the top PDPs after deploy warms the common ones), and do not read the
 * first post-deploy field measurement as a regression.
 */
const CDN_RUNGS = [240, 480, 640, 900, 1200, 1550] as const;

/** Shopify sizes via a `_WIDTHx` suffix on the filename, before the query. */
function cdnResize(url: string, width: number): string {
  const [base, query] = url.split("?");
  const sized = base.replace(/(\.[a-z]+)$/i, `_${width}x$1`);
  return query ? `${sized}?${query}` : sized;
}

/**
 * Image that:
 *  - serves a properly Lanczos-downscaled `srcset` (640w card / 1200w large) so
 *    the browser never naively shrinks a huge photo — this kills the moiré /
 *    "pixelated edges" on fine patterns (ties, checks, stripes);
 *  - loads the local file first and silently falls back to the Shopify CDN if
 *    the local file is ever missing.
 */
export function SmartImage({
  local,
  fallback,
  alt = "",
  className,
  sizes = "(max-width: 768px) 50vw, 25vw",
  priority = false,
  ...props
}: SmartImageProps) {
  const card = cardVariant(local);
  // In CDN mode the remote original (1550px) is the primary and gets its own
  // resize ladder; the local path stays the offline/dev source of truth.
  const cdnMode = USE_CDN && !!fallback;
  const primarySrc = cdnMode ? fallback! : local;
  const initialSrcSet = cdnMode
    ? CDN_RUNGS.map((w) => `${cdnResize(fallback!, w)} ${w}w`).join(", ")
    : card
      ? `${card} 640w, ${local} 1200w`
      : undefined;

  const [src, setSrc] = React.useState(primarySrc);
  const [srcSet, setSrcSet] = React.useState<string | undefined>(initialSrcSet);
  // Modern-codec <source> elements are dropped the moment anything fails, because
  // a <picture> does NOT auto-advance to the next <source> on a 404 — it just
  // errors the <img>. Clearing them lets the JPEG/CDN fallback actually take over.
  const [useModern, setUseModern] = React.useState(true);
  // Priority (LCP) images must NOT be gated behind the fade-in: starting them at
  // opacity:0 until onLoad defers the contentful paint behind hydration. They
  // render visible immediately; lazy images still fade in when they decode.
  const [loaded, setLoaded] = React.useState(priority);
  const triedFallback = React.useRef(false);
  const imgRef = React.useRef<HTMLImageElement>(null);

  // Reset when the target image changes (e.g. switching colour variant).
  React.useEffect(() => {
    setSrc(primarySrc);
    setSrcSet(initialSrcSet);
    setUseModern(true);
    triedFallback.current = false;
    // Cached images can finish loading before React attaches onLoad, which would
    // otherwise leave them stuck invisible. If already complete, reveal at once.
    const node = imgRef.current;
    setLoaded(priority || (!!node && node.complete && node.naturalWidth > 0));
  }, [primarySrc, initialSrcSet, priority]);

  // Modern codecs carry the SAME pixels at ~20-30% fewer bytes. Only offered
  // when we're still on the local JPEG ladder (the remote CDN has no twins).
  const onLocalLadder = useModern && !!srcSet && src === local;
  const modern = onLocalLadder && card
    ? {
        avif: `${asFormat(card, "avif")} 640w, ${asFormat(local, "avif")} 1200w`,
        webp: `${asFormat(card, "webp")} 640w, ${asFormat(local, "webp")} 1200w`,
      }
    : null;

  const img = (
    <img
      ref={imgRef}
      src={src}
      srcSet={srcSet}
      sizes={srcSet ? sizes : undefined}
      alt={alt}
      loading={priority ? "eager" : "lazy"}
      fetchPriority={priority ? "high" : "auto"}
      decoding="async"
      onLoad={() => setLoaded(true)}
      onError={() => {
        // Step 1: a modern-codec file is missing → drop the <source>s and retry
        // the original JPEG. Step 2: the JPEG is missing too → go to the CDN.
        if (useModern && onLocalLadder) {
          setUseModern(false);
          return;
        }
        // Whichever source we started on, fall back to the other one exactly
        // once: CDN mode retries the local file, local mode retries the CDN.
        const other = cdnMode ? local : fallback;
        if (!triedFallback.current && other && other !== src) {
          triedFallback.current = true;
          setSrcSet(undefined); // single src, no ladder on the fallback path
          setSrc(other);
        }
      }}
      className={cn(
        "h-full w-full object-cover transition-opacity duration-500",
        loaded ? "opacity-100" : "opacity-0",
        className
      )}
      {...props}
    />
  );

  if (!modern) return img;

  return (
    // `contents` = no box of its own, so every existing `h-full`/`absolute inset-0`
    // on the <img> keeps resolving against the original parent. Without it the
    // <picture> would introduce an inline box and collapse the image height.
    <picture className="contents">
      <source type="image/avif" srcSet={modern.avif} sizes={sizes} />
      <source type="image/webp" srcSet={modern.webp} sizes={sizes} />
      {img}
    </picture>
  );
}
