/**
 * Flatten the live home page into ONE self-contained .html file that opens by
 * double-click (no server, no JS): inlines the compiled CSS, base64-embeds the
 * fonts and images, strips all Next scripts, and forces images visible (the
 * SmartImage component starts at opacity:0 and only reveals via JS onLoad).
 *
 *   node scripts/flatten-home.mjs [http://localhost:5184] [outfile]
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const BASE = process.argv[2] || "http://localhost:5184";
const OUT = process.argv[3] || join(root, "..", "..", "..", "Downloads", "berto-lucci.html");
const PUB = join(root, "public");
const NEXT = join(root, ".next");

const mimeByExt = (f) => {
  const e = f.split(".").pop().toLowerCase();
  return e === "svg" ? "image/svg+xml"
    : e === "png" ? "image/png"
    : e === "webp" ? "image/webp"
    : e === "woff2" ? "font/woff2"
    : e === "woff" ? "font/woff"
    : "image/jpeg";
};
const dataUri = (file) => {
  const buf = readFileSync(file);
  return `data:${mimeByExt(file)};base64,${buf.toString("base64")}`;
};

const LANG = process.env.LANG_CODE || "gr"; // match the Greek preview by default
const text = async (p) => (await fetch(BASE + p)).text();

console.log(`→ fetching rendered HTML + CSS from ${BASE} (lang=${LANG})`);
let html = await (await fetch(BASE + "/", { headers: { Cookie: `bl_lang=${LANG}` } })).text();

// ---- 1. gather + inline the stylesheet(s) ----
const cssHrefs = [...html.matchAll(/<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"/g)].map((m) => m[1]);
let css = "";
for (const href of cssHrefs) css += (await text(href)) + "\n";

// ---- 2. inline @font-face woff2 from .next/static/media (offline fonts) ----
let fontHits = 0, fontMiss = 0;
css = css.replace(/url\((\/_next\/static\/media\/[^)?"']+\.woff2?)(\?[^)]*)?\)/g, (m, url) => {
  const file = join(NEXT, url.replace(/^\/_next\//, ""));
  if (existsSync(file)) { fontHits++; return `url(${dataUri(file)})`; }
  fontMiss++; return m;
});
console.log(`  fonts inlined: ${fontHits} (missing ${fontMiss})`);

// ---- 3. inline every local <img> as a base64 data URI (prefer the 640px card) ----
let imgHits = 0, imgMiss = 0;
const localToDataUri = (src) => {
  let rel = decodeURIComponent(src.split("?")[0]).replace(/^\//, "");
  let file = join(PUB, rel);
  const card = file.replace(/\.jpe?g$/i, "__card.jpg");
  if (/\.jpe?g$/i.test(file) && existsSync(card)) file = card; // smaller variant
  if (!existsSync(file)) { imgMiss++; return null; }
  imgHits++;
  return dataUri(file);
};
html = html.replace(/<img\b[^>]*>/g, (tag) => {
  let t = tag.replace(/\ssrcset="[^"]*"/g, "").replace(/\ssizes="[^"]*"/g, "");
  const src = (t.match(/\ssrc="([^"]+)"/) || [])[1];
  if (src && (src.startsWith("/bertolucci_images") || src.startsWith("/brand"))) {
    const d = localToDataUri(src);
    if (d) t = t.replace(/\ssrc="[^"]+"/, ` src="${d}"`);
  }
  return t;
});
console.log(`  images inlined: ${imgHits} (missing ${imgMiss})`);

// ---- 4. strip all scripts + next asset links; inject the inlined CSS + fixes ----
html = html
  .replace(/<script[\s\S]*?<\/script>/g, "")
  .replace(/<link[^>]+rel="stylesheet"[^>]*>/g, "")
  .replace(/<link[^>]+rel="preload"[^>]*>/g, "")
  .replace(/<link[^>]+rel="modulepreload"[^>]*>/g, "")
  .replace(/<link[^>]+href="\/_next[^>]*>/g, "")
  // dev absolute URLs (e.g. og:image) → the real production domain
  .replace(/http:\/\/localhost:\d+/g, "https://www.bertolucci.com.gr");

const fixes = `
/* --- flatten fixes: reveal SmartImage (JS-less) + keep entrance anims --- */
img{opacity:1 !important}
.reveal,.reveal-zoom,.reveal-lift{opacity:1 !important}
html{scroll-behavior:auto}
`;
html = html.replace("</head>", `<style>${css}\n${fixes}</style></head>`);

// A friendly banner comment
html = html.replace(/^<!doctype html>/i, "<!doctype html>\n<!-- Berto Lucci — self-contained static snapshot of the home page. Generated by scripts/flatten-home.mjs. Interactivity/other pages require the Next.js dev server. -->");

writeFileSync(OUT, html);
const kb = (Buffer.byteLength(html) / 1024 / 1024).toFixed(2);
console.log(`✓ wrote ${OUT} (${kb} MB)`);
